### ISSUE TITLE
Running rb2db from Jenkins caused an undefined method "this" in duffy-0.3.5

### ISSUE THREAD

**Issue by duffyjp** [duffyjp/duffy#3]
```
Bundle complete! 32 Gemfile dependencies, 102 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
/var/lib/jenkins/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x930a1c duffy-0.3.5> (NoMethodError)
	from /var/lib/jenkins/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /var/lib/jenkins/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /var/lib/jenkins/.rvm/gems/ruby-2.3.1/gems/rb2db-0.2.2/exe/rb2db:2:in `<top (required)>'
	from /var/lib/jenkins/.rvm/gems/ruby-2.3.1/bin/rb2db:23:in `load'
	from /var/lib/jenkins/.rvm/gems/ruby-2.3.1/bin/rb2db:23:in `<main>'
	from /var/lib/jenkins/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /var/lib/jenkins/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Created database 'db/test.sqlite32'

**Comment by duffyjp** [comment]
Looks like this bug: https://github.com/rubygems/rubygems/issues/1420

Fresh Ubuntu 16.04 with Rubygems via RVM install is `2.5.1` which is the same version everyone is talking about in the report.  Updating via `gem update --system` gives `2.6.14`

With 2.6.14 everything works as expected.

I'll add `gem update --system` to all my Jenkins Build scripts.
